spring.application.name=OAuth2

spring.security.oauth2.client.registration.google.client-id=************************************
spring.security.oauth2.client.registration.google.client-secret=********************************
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.path=/h2-console
spring.h2.console.enabled=true